repos:
- repo: https://github.com/pre-commit/pre-commit-hooks
  rev: v5.0.0
  hooks:
    - id: trailing-whitespace
    - id: end-of-file-fixer
    - id: check-yaml
      exclude: ^cloudformation/.*\.yaml$
    - id: check-added-large-files
    - id: check-json
    - id: check-merge-conflict
    - id: debug-statements

- repo: https://github.com/astral-sh/ruff-pre-commit
  rev: v0.9.9
  hooks:
    - id: ruff
      args: [
        "--fix",
        "--exit-non-zero-on-fix",
        "--unsafe-fixes",
      ]
      exclude: |
        (?x)(
          ^tests/loader/test_loader\.py$|
          ^terraform/.*\.py$|
          ^scripts/.*\.py$|
          ^tests/test_config\.py$
        )
    - id: ruff-format
      exclude: |
        (?x)(
          ^terraform/.*\.py$|
          ^scripts/.*\.py$
        )

- repo: https://github.com/pre-commit/mirrors-mypy
  rev: v1.15.0
  hooks:
    - id: mypy
      additional_dependencies: [
        types-boto3,
        types-requests,
        pytest,
        pydantic,
        typer,
        snowflake-connector-python,
        types-python-dateutil
      ]
      exclude: |
        (?x)(
          ^terraform/|
          ^scripts/
        )
      args: [
        "--config-file=pyproject.toml",
        "--explicit-package-bases",
        "--ignore-missing-imports"
      ]
      # Run on every commit - settings defined in pyproject.toml

# - repo: https://github.com/bridgecrewio/checkov.git
#   rev: 3.2.379
#   hooks:
#     - id: checkov
#       args: [--soft-fail, --framework, terraform]
#       files: \.tf$

- repo: https://github.com/antonbabenko/pre-commit-terraform
  rev: v1.97.4
  hooks:
    - id: terraform_fmt
    # Commenting out terraform_validate as it's failing with non-critical issues
    - id: terraform_validate
      args:
        - --hook-config=--retry-once-with-cleanup=true

- repo: local
  hooks:

    - id: pytest-check-fast
      name: pytest-fast
      entry: poetry run pytest -xvs tests/ --durations=3 -m "not slow" --no-cov -k "not TestSnowflakeService.test_connect_success"
      language: system
      pass_filenames: false
      always_run: true
      # This will run on every commit - only fast unit tests

    - id: pytest-check
      name: pytest-check
      entry: poetry run pytest
      language: system
      pass_filenames: false
      always_run: true

    # Add our custom fix scripts as optional hooks
    - id: fix-all
      name: Fix all linting issues
      entry: poetry run python scripts/fix_all.py
      language: system
      pass_filenames: false
      always_run: true
      stages: [manual]  # Only run when explicitly requested
      description: "Fix all linting issues automatically (run with: pre-commit run fix-all --hook-stage manual)"

    - id: fix-mypy
      name: Fix mypy issues
      entry: poetry run python scripts/fix_mypy_issues.py
      language: system
      pass_filenames: false
      always_run: true
      stages: [manual]  # Only run when explicitly requested
      description: "Fix mypy issues automatically (run with: pre-commit run fix-mypy --hook-stage manual)"

    - id: fix-ruff
      name: Fix Ruff issues
      entry: poetry run python scripts/fix_ruff.py
      language: system
      pass_filenames: false
      always_run: true
      stages: [manual]  # Only run when explicitly requested
      description: "Fix Ruff issues automatically (run with: pre-commit run fix-ruff --hook-stage manual)"

- repo: https://github.com/PyCQA/bandit
  rev: 1.8.3
  hooks:
    - id: bandit
      args: ["-c", "pyproject.toml", "--severity-level", "high", "--confidence-level", "high"]
      additional_dependencies: ["bandit[toml]"]
      exclude: ^terraform/|^scripts/
      # Run on push or manually to avoid slowing down every commit

# Add these additional security hooks but only for critical checks
- repo: https://github.com/Lucas-C/pre-commit-hooks-safety
  rev: v1.4.0
  hooks:
    - id: python-safety-dependencies-check
      files: pyproject.toml
      # Only run on push or manually

- repo: https://github.com/Yelp/detect-secrets
  rev: v1.5.0
  hooks:
    - id: detect-secrets
      exclude: |
        (?x)(
          poetry.lock|
          package-lock.json|
          ^tests/.*|
          ^\.env\.example$|
          .*\.md$|
          .*\.ini$|
          ^\.mypy_cache/.*|
          ^\.pytest_cache/.*|
          ^htmlcov/.*|
          ^conftest\.py$|
          ^scripts/.*|
          ^terraform/.*
        )
      args: ['--baseline', '.secrets.baseline']
